[package]
name = "state"
version = "0.1.0"
authors = ["Damien Radtke <damienradtke@gmail.com>"]

[lib]
name = "state"
# crate-type = ["dylib"]

[dependencies.allegro]
version = "=0.0.22"

[dependencies.allegro_font]
version = "=0.0.22"

[dependencies.allegro_image]
version = "=0.0.22"
